// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbkb_JevCUXxpD7COcat2xwXyhmjAnssc',
    appId: '1:746797788978:web:a0e37fc49a5481b5cd312b',
    messagingSenderId: '746797788978',
    projectId: 'exam-b7cee',
    authDomain: 'exam-b7cee.firebaseapp.com',
    storageBucket: 'exam-b7cee.appspot.com',
    measurementId: 'G-QTLGBYNEH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH4ilTrbbmkHW0pRG1CMS1DeQL0wHwb2k',
    appId: '1:746797788978:android:cc55c1ab671ed7f1cd312b',
    messagingSenderId: '746797788978',
    projectId: 'exam-b7cee',
    storageBucket: 'exam-b7cee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP9ccuZ00gTqvfi36OwiC3sWWDWRrKHwI',
    appId: '1:746797788978:ios:aa406333aeffab77cd312b',
    messagingSenderId: '746797788978',
    projectId: 'exam-b7cee',
    storageBucket: 'exam-b7cee.appspot.com',
    iosBundleId: 'com.example.examtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP9ccuZ00gTqvfi36OwiC3sWWDWRrKHwI',
    appId: '1:746797788978:ios:a5596df6ba69f332cd312b',
    messagingSenderId: '746797788978',
    projectId: 'exam-b7cee',
    storageBucket: 'exam-b7cee.appspot.com',
    iosBundleId: 'com.example.examtest.RunnerTests',
  );
}
